# Site settings
title: Carlos Codes Blog
email: carlos.raiti.mendoza@gmail.com
description: "I've always had a passion for learning, teaching, and technology. This blog documents some of my key learnings as a Software Developer."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: carlosrmendoza
github_username:  carlos-r-mendoza

# Build settings
markdown: kramdown
permalink: /:title
